video/drm: display: Fix compile errors if CONFIG_ROCKCHIP_RESOURCE_IMAGE is disabled
Some functions will not be used if CONFIG_ROCKCHIP_RESOURCE_IMAGE is
disabled, such as bitmap_create(), bitmap_get_buffer() and so on.

Therefore, add config macro CONFIG_ROCKCHIP_RESOURCE_IMAGE check for
these functions to avoid complie errors like:

......
drivers/video/drm/rockchip_display.c:1478:14: error: ‘bitmap_create’
defined but not used [-Werror=unused-function]
 static void *bitmap_create(int width, int height, unsigned int state)
              ^~~~~~~~~~~~~
......

Change-Id: I156e88951769bb807c7479d2fdc2cb999cb76bc0
Signed-off-by: Damon Ding <damon.ding@rock-chips.com>